name: billbook
description: A Flutter based Bill Book Web App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  responsive_builder: ^0.2.0+2
  provider: ^4.3.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  flutter_icons: ^1.1.0
  flushbar: ^1.10.4
  pdf: ^1.13.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
